// This file has been generated by svg2code

function svg2code_draw(context, id, x, y, width, height)
{
    context.strokeStyle = '#ff0000';
    context.beginPath();
    context.moveTo(125, 125);
    context.lineTo(125, 45);
    context.lineTo(45, 125);
    context.closePath();
    context.stroke();
}
